---
- name: Check repo
  shell: yum list rabbitmq-server
  ignore_errors: yes
  register: repo_installed
  changed_when: false

- name: Install repo
  yum: name=epel-release
  sudo: yes
  when: repo_installed.rc != 0

- yum: name=rabbitmq-server
  sudo: yes

- name: Check plug-in(MQTT)
  shell: /usr/sbin/rabbitmq-plugins list rabbitmq_mqtt | grep "[E]"
  ignore_errors: yes
  register: mqtt_enabled
  changed_when: false

- name: Enable plug-in(MQTT)
  shell: /usr/sbin/rabbitmq-plugins enable rabbitmq_mqtt
  sudo: yes
  when: mqtt_enabled.rc != 0

- name: Check plug-in(Manager)
  shell: /usr/sbin/rabbitmq-plugins list rabbitmq_management | grep "[E]"
  ignore_errors: yes
  register: management_enabled
  changed_when: false

- name: Enable plug-in(Manager)
  shell: /usr/sbin/rabbitmq-plugins enable rabbitmq_management
  sudo: yes
  when: management_enabled.rc != 0

- service: name=rabbitmq-server enabled=yes state=started
  sudo: yes
