---
- name: Check repo
  shell: yum list rabbitmq-server
  ignore_errors: yes
  register: repo_installed
  changed_when: false

- name: Install repo
  yum: name=epel-release
  sudo: yes
  when: repo_installed.rc != 0

- yum: name=rabbitmq-server
  sudo: yes

- name: Check plug-in(MQTT)
  shell: /usr/sbin/rabbitmq-plugins list rabbitmq_mqtt | grep "[E]"
  ignore_errors: yes
  register: mqtt_enabled
  changed_when: false

- name: Enable plug-in(MQTT)
  shell: /usr/sbin/rabbitmq-plugins enable rabbitmq_mqtt
  sudo: yes
  when: mqtt_enabled.rc != 0

- name: Check plug-in(WebSocket)
  shell: /usr/sbin/rabbitmq-plugins list rabbitmq_web_stomp | grep "[E]"
  ignore_errors: yes
  register: mqtt_enabled
  changed_when: false

- name: Enable plug-in(WebSocket)
  shell: /usr/sbin/rabbitmq-plugins enable rabbitmq_web_stomp
  sudo: yes
  when: mqtt_enabled.rc != 0

- name: Check plug-in(Manager)
  shell: /usr/sbin/rabbitmq-plugins list rabbitmq_management | grep "[E]"
  ignore_errors: yes
  register: management_enabled
  changed_when: false

- name: Enable plug-in(Manager)
  shell: /usr/sbin/rabbitmq-plugins enable rabbitmq_management
  sudo: yes
  when: management_enabled.rc != 0

- name: Copy cookie
  copy: src=".erlang.cookie" dest="/var/lib/rabbitmq/.erlang.cookie" owner=rabbitmq group=rabbitmq mode=0400
  sudo: yes

- service: name=rabbitmq-server enabled=yes state=started
  sudo: yes

- name: Check cluster
  shell: rabbitmqctl cluster_status | grep "rabbit@{{ master_node_hostname }}"
  sudo: yes
  ignore_errors: yes
  register: cluster_created
  when: inventory_hostname != "{{ master_node_hostname }}"
  changed_when: false

- name: Cluster settings
  shell: >-
    rabbitmqctl cluster_status &&
    rabbitmqctl stop_app &&
    rabbitmqctl reset &&
    rabbitmqctl join_cluster rabbit@{{ master_node_hostname }} &&
    rabbitmqctl start_app
  sudo: yes
  sudo_user: rabbitmq
  when: inventory_hostname != "{{ master_node_hostname }}" and cluster_created.rc != 0

- name: Check publisher user
  shell: rabbitmqctl list_users | grep "{{ publisher.user }}"
  sudo: yes
  ignore_errors: yes
  register: publisher_user_created
  when: inventory_hostname != "{{ master_node_hostname }}"
  changed_when: false

- name: Check virtual host
  shell: rabbitmqctl list_vhosts | grep "{{ vhost.name }}"
  sudo: yes
  ignore_errors: yes
  register: vhost_created
  when: inventory_hostname != "{{ master_node_hostname }}"
  changed_when: false

- name: Add virtual host
  shell: >-
    rabbitmqctl add_vhost {{ vhost.name }}
  sudo: yes
  sudo_user: rabbitmq
  when: inventory_hostname != "{{ master_node_hostname }}" and vhost_created.rc != 0

- name: Add publisher user
  shell: >-
    rabbitmqctl add_user {{ publisher.user }} {{ publisher.password }} &&
    rabbitmqctl set_permissions -p {{ vhost.name }} {{ publisher.user }} ".*" ".*" ".*"
  sudo: yes
  sudo_user: rabbitmq
  when: inventory_hostname != "{{ master_node_hostname }}" and publisher_user_created.rc != 0

- name: Check subscriber user
  shell: rabbitmqctl list_users | grep "{{ subscriber.user }}"
  sudo: yes
  ignore_errors: yes
  register: subscriber_user_created
  when: inventory_hostname != "{{ master_node_hostname }}"
  changed_when: false

- name: Add subscriber user
  shell: >-
    rabbitmqctl add_user {{ subscriber.user }} {{ subscriber.password }} &&
    rabbitmqctl set_permissions -p {{ vhost.name }} {{ subscriber.user }} ".*" ".*" ".*"
  sudo: yes
  sudo_user: rabbitmq
  when: inventory_hostname != "{{ master_node_hostname }}" and subscriber_user_created.rc != 0
