---
- name: Check repo
  command: yum list mosquitto
  ignore_errors: yes
  register: repo_installed
  changed_when: false

- name: Install repo
  shell:
    wget http://download.opensuse.org/repositories/home:/oojah:/mqtt/CentOS_CentOS-7/home:oojah:mqtt.repo
  sudo: yes
  args:
    chdir: /etc/yum.repos.d
  when: repo_installed.rc != 0

- yum: name=mosquitto
  sudo: yes
